### ISSUE TITLE
Specify license of the music files

### ISSUE THREAD

**Issue by akien-mga** [AlexAUT/Kroniax#14]
Currently the README.md only specifies that the game is under the MIT license.

However, the music files are from various artists, and I guess they were not originally licensed under the MIT license. Their original license should be specified too (and if they are nonfree/freeware, a replacement might need to be looked for).

**Comment by AlexAUT** [comment]
I have the permission to use it from MafiaFLairBeats (He hasn't specified a license...), and for the machinima sounds I have included a link to their licensing page
